### ISSUE TITLE
exportの変数展開

### ISSUE THREAD

**Issue by nktr-cp** [Wolframike/minishell#63]

**Comment by Wolframike** [comment]
exportの各引数を別々に変数展開し、'='の前後を判定して処理するべき
一気に展開しようとすると切れ目がわからない('='がない場合も複数ある場合もあるため、'+='にも対応するならなおさら)

**Comment by Wolframike** [comment]
各ノードのcontentsを展開し、スペースとスペースの間を引数として読み、各個処理するような2重ループでいい
最初の一回のみ"export"の文字列を飛ばすこと

**Comment by Wolframike** [comment]
あきらめた
